// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Book defines model for Book.
type Book struct {
	// Author Book author
	Author string `json:"author"`

	// Id Unique book identifier
	Id int32 `json:"id"`

	// Isbn ISBN number
	Isbn string `json:"isbn"`

	// Title Book title
	Title string `json:"title"`
}

// BookInput defines model for BookInput.
type BookInput struct {
	// Author Book author
	Author string `json:"author"`

	// Isbn ISBN number
	Isbn string `json:"isbn"`

	// Title Book title
	Title string `json:"title"`
}

// BooksResponse defines model for BooksResponse.
type BooksResponse struct {
	// Books List of books
	Books []Book `json:"books"`

	// Limit Number of books per page
	Limit int32 `json:"limit"`

	// Page Current page number
	Page int32 `json:"page"`

	// Total Total number of books available
	Total int32 `json:"total"`

	// TotalPages Total number of pages
	TotalPages int32 `json:"totalPages"`
}

// Error defines model for Error.
type Error struct {
	// Message Error message
	Message string `json:"message"`
}

// GetAllBooksParams defines parameters for GetAllBooks.
type GetAllBooksParams struct {
	// Page Page number (1-indexed)
	Page *int32 `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of books per page
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateBookJSONRequestBody defines body for CreateBook for application/json ContentType.
type CreateBookJSONRequestBody = BookInput

// UpdateBookJSONRequestBody defines body for UpdateBook for application/json ContentType.
type UpdateBookJSONRequestBody = BookInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all books
	// (GET /books)
	GetAllBooks(ctx echo.Context, params GetAllBooksParams) error
	// Create a new book
	// (POST /books)
	CreateBook(ctx echo.Context) error
	// Delete a book
	// (DELETE /books/{id})
	DeleteBook(ctx echo.Context, id int32) error
	// Get a book by ID
	// (GET /books/{id})
	GetBookByID(ctx echo.Context, id int32) error
	// Update a book
	// (PUT /books/{id})
	UpdateBook(ctx echo.Context, id int32) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAllBooks converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllBooks(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllBooksParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllBooks(ctx, params)
	return err
}

// CreateBook converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBook(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBook(ctx)
	return err
}

// DeleteBook converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBook(ctx, id)
	return err
}

// GetBookByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetBookByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBookByID(ctx, id)
	return err
}

// UpdateBook converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBook(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/books", wrapper.GetAllBooks)
	router.POST(baseURL+"/books", wrapper.CreateBook)
	router.DELETE(baseURL+"/books/:id", wrapper.DeleteBook)
	router.GET(baseURL+"/books/:id", wrapper.GetBookByID)
	router.PUT(baseURL+"/books/:id", wrapper.UpdateBook)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYXW/bNhT9KwTXhw5TLDlxsFZPa+qiMJAVWZI+FRlAS9cyO/Gj5KUbo/B/H0jKshWp",
	"TTq0jYH1KbF1eT/PObzyJ1oooZUEiZbmn6gtliBY+PdMqX/8X22UBoMcwrfM4VIZ/18JtjBcI1eS5sGa",
	"NA8TCrdM6BpoTl/UTJKpkmrFJE2oYLfnICtc0vz49DShgsvt53FCca39GYuGy4puEsrLfqS3kn9wQOY+",
	"IC9BIl9w6AQdJ3ShjGBIc8olnhzT1jWXCBWY4NvOZd/77OrsDZFOzLsu6fPfnx1l45PJ+Hk2mWR3Ksm6",
	"hWQJ1QwRjHf497vs6PnRzW9P6EB9yNF7H2xmfLafw/USyGtFLoyqDBOCy4qcM1k5VsHXtnaTUAMfHDdQ",
	"0vyd7/M2mYS2UwwdumnPqvl7KNCn7fObSe3w0fHxc4btDL9ufPYSrFbSQn+Enlm2X9A5t0jUgsTHCeUI",
	"Ipg9MbCgOf0l3UlJ2uhIGkRk0+bAjGFr/7nmgmM/xpswtDYK0WCIjq1pW3h8+iB6h2O9AC+dMSAxOB2A",
	"yMOUAxWyuu/72n/dON2VwFaM12zehcE4y7Ls4bEuWAX2/oA6mO2FmTwoyB0cbecbq2wauZ1YJ6EhbL0y",
	"JtK/iykB1g4OJNiT7eN9pgQCSYVkoZws6X3w37roJ+UtuVwoH7xQElkRkAeC8dr7c1org380kUeFEjSh",
	"kokgTxczchUNaEKd8QeWiNrmaVpxXLq5t0/XyhlnwfhTaa1YeYRgQz+61b4g2qjSFf7jkQFWrsnlq6vr",
	"hauJj7TwrWCSVV4WInw+clySC2WxMnD11zlhsiSXUHIbRlJAw+Am3T9n1700lQZplTMFjJSp0uaQTb3t",
	"Tr6iKPgsaEJXYGxMeDzKRpk3816Y5jSnJ6NsdBJwgcsw27QVjAoGOH0JaDisYL8g7Utk3oA8LVixhDLU",
	"fkoElw7BEi5jlb/SENoE21lJc/oa8EVdnzUg1cwwAQjG0vzd3cgXO5KTp+MjLku4hdK75P7xBwdmvRt1",
	"g/OoXLGMBXM1DquC4JILJ/Z1eY9QX6FrQ6lsuTaQy6D6CXbbJJNl96R241kTlT+M7DjLtrwAGabHtK55",
	"ERqevrdK7tbCh4j97l4JvOu24coVBVjr4W5as4ROvmEOUX8GYs/kitW83IfeHng2CT39MVn4lYLVxIJZ",
	"gSHQGCbUOiGYWUeEE1bX7UWLrLI7Yb7xd5uyA0R7aYAhEEYkfIzrceBaIHjS7F5JEBC/IPWIFY+HCzsq",
	"K1g8U+X6m8Ijbo2brnijcbDp4XL8TQMPDSPcMEUouyS2xWa9/uGgbNp9UDDswWkAipukUf/0Ey83EZI1",
	"4MA9Pw3fExaBOV+T2bSHwGjTIPCLyh4mFzwE+fRX0U49w8tMF137Unr/PtTXyMln9vtY7SODZzaNISff",
	"P+SdneyQ4NoB2KBqfnk7YcRyWdXQApSjJbPpf9lPfJfO1gGeB4Xi7Lsr6iFc8D/p0C4RXbEd2CPcACPe",
	"6jLoviRwyy1uX0U+o9nR+kA0+9F3luzH7CwuNP1wdpb/O9m2lPnsmuStw/EhYkxhBbXSAiQ2QTrv8Hma",
	"1qpg9VJZzJ9lz/zreO9Nt/1VYciDzdOUaT7a/4XDE6ZJc5Co4WcICDm1hLc7vsbKNjebfwMAAP//f2vv",
	"LEEYAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
