// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Book defines model for Book.
type Book struct {
	// Author Book author
	Author string `json:"author"`

	// Id Unique book identifier
	Id int32 `json:"id"`

	// Isbn ISBN number
	Isbn string `json:"isbn"`

	// Title Book title
	Title string `json:"title"`
}

// BookInput defines model for BookInput.
type BookInput struct {
	// Author Book author
	Author string `json:"author"`

	// Isbn ISBN number
	Isbn string `json:"isbn"`

	// Title Book title
	Title string `json:"title"`
}

// Error defines model for Error.
type Error struct {
	// Message Error message
	Message string `json:"message"`
}

// CreateBookJSONRequestBody defines body for CreateBook for application/json ContentType.
type CreateBookJSONRequestBody = BookInput

// UpdateBookJSONRequestBody defines body for UpdateBook for application/json ContentType.
type UpdateBookJSONRequestBody = BookInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all books
	// (GET /books)
	GetAllBooks(ctx echo.Context) error
	// Create a new book
	// (POST /books)
	CreateBook(ctx echo.Context) error
	// Delete a book
	// (DELETE /books/{id})
	DeleteBook(ctx echo.Context, id int32) error
	// Get a book by ID
	// (GET /books/{id})
	GetBookByID(ctx echo.Context, id int32) error
	// Update a book
	// (PUT /books/{id})
	UpdateBook(ctx echo.Context, id int32) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAllBooks converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllBooks(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAllBooks(ctx)
	return err
}

// CreateBook converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBook(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBook(ctx)
	return err
}

// DeleteBook converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteBook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteBook(ctx, id)
	return err
}

// GetBookByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetBookByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBookByID(ctx, id)
	return err
}

// UpdateBook converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateBook(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int32"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateBook(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/books", wrapper.GetAllBooks)
	router.POST(baseURL+"/books", wrapper.CreateBook)
	router.DELETE(baseURL+"/books/:id", wrapper.DeleteBook)
	router.GET(baseURL+"/books/:id", wrapper.GetBookByID)
	router.PUT(baseURL+"/books/:id", wrapper.UpdateBook)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXX2/bNhD/KsStDxumWHLiYImelsxFYSAbsiR9KjKAls4yO4lk+ceNEei7D0fJdhQp",
	"yzq0jYH2yZJ1f35397s78h4yVWklUToL6T3YbIkVD4/nSv1Nv9oojcYJDP9y75bK0FOONjNCO6EkpEGa",
	"tR8jwDte6RIhhbOSSzZVUq24hAgqfneBsnBLSA+PjyOohNy8jyNwa0061hkhC6gjEHnf01spPnhkc3Io",
	"cpROLAR2nI4jWChTcQcpCOmODmFrWkiHBZpg285l3/rs+vwPJn0175qE019ODpLx0WR8mkwmyaNIkm4g",
	"SQSaO4eGDP71Ljk4Pbj9+RUMxOeEI+uDyWy+PcRws0T2RrFLowrDq0rIgl1wWXhe4Kemto7A4AcvDOaQ",
	"vqM8b8BEsK1iyNDtVlfN32PmCDbhm0nt3Yvz43sNtzX87+V7bUxTom7pKrSWYPRCCfJs8/lhNCFIqRxb",
	"KC9zeA7ixkQfFEkKuVDkPFPS8SxwCysuSrLntVbG/dp6HmWqgggkrwKFLmfsuhGACLwhhaVz2qZxXAi3",
	"9HOSj9fKG2/RkFZcKp4fOLQhH91oz5g2KvcZvR4Y5PmaXb2+vln4kpGnBaWCS15Q6WgIWfZRuCW7VNYV",
	"Bq//vGBc5uwKc2EhglJkKG1Iagv399lND6bSKK3yJsORMkXcKtmYZHcUC+m2hAIiWKGxDeDxKBklJEZW",
	"uBaQwtEoGR1BoPAy1DYOSOmpQNev8BU6I3CFjJdlG9SPGc+WmId4j1klpHdomZBNZD9BcGc4GZjlkMIb",
	"dGdlGRACVd1qRSGQr8Mk2dQVZfDOtS5FFpTj91bJ3eqhJ+GwCoqvDC4ghR/i3ZKK2w0Vh/VUb4nEjeHr",
	"hkfd0K59lqG1VL4NKFI7/kRM/wal6acB3zNJA4SXzKJZoWHYCkZgfVVxs27ytss6dRAvLPVK835bR6CV",
	"HSjZbwa5Q8aZxI/NMgw0DFSJ2kkbBSrSOOyVq1EPSWx6FK07V/n6syVltyPq7hhwxmPdY8j4szoeKkaY",
	"VVkIO2d2y4pyTXSYfB06rHgpctame69o2KPTABXrqJ0j8b3I64aSJbqBjTEN/zPeEHO+ZrNpj4GNTMtA",
	"zQ2v0KEhh4OrNFgQ9EpDbTf9w9Gly67oQcKePQjWtz0uTp7Y5k20L0ye2bRxOfnyLh9t932ia4dgg1Pz",
	"mT3HrJBFiVuCCmfZbPp/th5l6Xwd6LlXLE6++ER9YrV+b4eXOUR0h+3AOcIPdMRbnYe5LxneCes2h9on",
	"ZnYjvScz+8XPLMnXObP4kPT9ObN86822aZknj0kkHdSHGmOKKyyVrlC61knnNpjGcakyXi6VdelJckIX",
	"u8cmLrf30yELdJ/kWowe3pWpYVqYg40aLrQYMG0b3u76tYmsvq3/CQAA//+lFkWqLxQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
